version: '3.5'

services:
  rabbitmq:
    container_name: test_rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_PASS: devuser
      RABBITMQ_DEFAULT_USER: devuser
    ports:
      - 15673:15672
      - 5673:5672
    networks:
      - test-amqp-cm-network
    volumes:
      - test-amqp-cm-volume:/var/lib/rabbitmq

networks:
  test-amqp-cm-network:
    driver: bridge

volumes:
  test-amqp-cm-volume:
